#
#  ----- BEGIN LICENSE BLOCK -----
#  ----- END LICENSE BLOCK -----
#

GDP_SRC_ROOT=	../../..
ADM=		${GDP_SRC_ROOT}/adm

UPDATE_LICENSE=	${ADM}/update-license.sh

update-license:
	${UPDATE_LICENSE} Makefile *.py
