#!/bin/sh

major=$1
minor=$2
patch=$3

#
#  Create a new gdp_version.h file from template
#

{
	echo "// DO NOT EDIT THIS FILE.  IT IS AUTOGENERATED"
	sed	-e "s/@GDP_VERSION_MAJOR@/$major/" \
		-e "s/@GDP_VERSION_MINOR@/$minor/" \
		-e "s/@GDP_VERSION_PATCH@/$patch/" \
		gdp_version.template
	echo "// DO NOT EDIT THIS FILE.  IT IS AUTOGENERATED"
} > _gdp_version_$$

if [ ! -e gdp_version.h ] || ! cmp -s _gdp_version_$$ gdp_version.h
then
	test -e gdp_version.h && diff _gdp_version_$$ gdp_version.h
	cp _gdp_version_$$ gdp_version.h
fi

rm _gdp_version_$$
